---
Attribute:
  enabled: false
  exclude: []
BooleanParameter:
  enabled: true
  exclude: []
ClassVariable:
  enabled: true
  exclude: []
ControlParameter:
  enabled: true
  exclude:
  - Substation::Chain::DSL#default_chain # TODO refactor
DataClump:
  enabled: true
  exclude: []
  max_copies: 2
  min_clump_size: 2
DuplicateMethodCall:
  enabled: true
  exclude: []
  max_calls: 1
  allow_calls: []
FeatureEnvy:
  enabled: true
  exclude:
  - Substation::Chain#call # loops over instance state
  - Substation::Chain::Incoming#result # defined in a module
  - Substation::Chain::Outgoing#respond_with #defined in a module
  - Substation::Processor::Evaluator#call # method object
  - Substation::Processor::Evaluator#on_success # method object
  - Substation::Chain#outgoing? # TODO refactor
IrresponsibleModule:
  enabled: true
  exclude: []
LongParameterList:
  enabled: true
  exclude:
  - Substation::Dispatcher#call
  - Substation::Chain::DSL::Builder#define_dsl_method
  max_params: 2
LongYieldList:
  enabled: true
  exclude: []
  max_params: 2
NestedIterators:
  enabled: true
  exclude:
  - Substation::Chain::DSL::Builder#define_dsl_method
  max_allowed_nesting: 1
  ignore_iterators: []
NilCheck:
  enabled: true
  exclude: []
RepeatedConditional:
  enabled: true
  exclude: []
  max_ifs: 1
TooManyInstanceVariables:
  enabled: true
  exclude:
  - Substation::Response
  - Substation::Processor::Evaluator
  max_instance_variables: 3
TooManyMethods:
  enabled: true
  exclude:
  - Substation::Chain::DSL
  max_methods: 4
TooManyStatements:
  enabled: true
  exclude:
  - Substation::Utils#self.const_get
  - Substation::Utils#self.symbolize_keys
  - Substation::Dispatcher::Action#self.coerce
  - Substation::Chain#call
  - Substation::Utils#self.coerce_callable
  - Substation::Processor::Evaluator#call
  max_statements: 3
UncommunicativeMethodName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^[a-z]$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UncommunicativeModuleName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  accept: []
UncommunicativeParameterName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UncommunicativeVariableName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UnusedParameters:
  enabled: true
  exclude: []
UtilityFunction:
  enabled: true
  exclude:
  - Substation::Chain::Incoming#result # defined in a module
  - Substation::Chain::Outgoing#respond_with # defined in a module
  - Substation::Processor::Evaluator#on_success # inside a method object
  - Substation::Chain#outgoing? # TODO refactor
  max_helper_calls: 0
