---
Attribute:
  enabled: false
  exclude: []
BooleanParameter:
  enabled: true
  exclude: []
ClassVariable:
  enabled: true
  exclude: []
ControlParameter:
  enabled: true
  exclude: []
DataClump:
  enabled: true
  exclude:
  - Substation::Processor::Evaluator # FIXME
  max_copies: 2
  min_clump_size: 2
DuplicateMethodCall:
  enabled: true
  exclude:
  - !ruby/regexp /^Substation::DSL::Registry#\[\]=$/ # reek won't emit this anymore soon
  - Substation::Chain::Definition#prepend # reek won't emit this anymore soon
  - Substation::Chain::Definition#replace_failure_chain # replaces object at given idx inside an array
  max_calls: 1
  allow_calls: []
FeatureEnvy:
  enabled: true
  exclude:
  - Substation::Chain#call # loops over instance state
  - Substation::Processor::Outgoing#respond_with #defined in a module
  - Substation::Processor::Evaluator#call # method object
  - Substation::Processor::Evaluator#on_success # method object
  - Substation::Processor#success? # in a module to be included in a method object
  - Substation::Chain::DSL#__call__ # relies heavily on #new(other)
IrresponsibleModule:
  enabled: true
  exclude: []
LongParameterList:
  enabled: true
  exclude:
  - Substation::Dispatcher#call
  - Substation::Chain#self.exception_response # 3
  - Substation::Chain#on_exception # 3
  - Substation::Environment::DSL#register
  - Substation::Environment#register # 3
  - Substation::Processor::Builder#call # 3
  max_params: 2
LongYieldList:
  enabled: true
  exclude: []
  max_params: 2
NestedIterators:
  enabled: true
  exclude:
  - Substation::Chain::DSL::ModuleBuilder#define_dsl_method
  max_allowed_nesting: 1
  ignore_iterators: []
NilCheck:
  enabled: true
  exclude: []
RepeatedConditional:
  enabled: true
  exclude: []
  max_ifs: 1
TooManyInstanceVariables:
  enabled: true
  exclude:
  - Substation::Response
  - Substation::Processor::Evaluator
  - Substation::Environment # 4
  max_instance_variables: 3
TooManyMethods:
  enabled: true
  exclude:
  - Substation::Chain::DSL # 7
  - Substation::Chain::Definition # 8
  - Substation::Environment # 5
  - Substation::DSL::Registry # 10
  max_methods: 4
TooManyStatements:
  enabled: true
  exclude:
  - Substation::Chain#call
  - Substation::Processor::Evaluator#call
  - Substation::Dispatcher::DSL#dispatch
  - Substation::Environment#self.build # ~5
  - Substation::Environment::DSL#register # 4
  - Substation::Chain::Definition#<< # 4
  max_statements: 3
UncommunicativeMethodName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^[a-z]$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UncommunicativeModuleName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  accept: []
UncommunicativeParameterName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UncommunicativeVariableName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UnusedParameters:
  enabled: true
  exclude: []
UtilityFunction:
  enabled: true
  exclude:
  - Substation::Processor::Outgoing#respond_with # defined in a module
  - Substation::Processor::Evaluator::Handler#respond_with # defined in a module
  - Substation::Processor::Evaluator#on_success # inside a method object
  - Substation::Processor#success? # in a module to be included in a method object
  - Substation::Environment#action # DSL method
  - Substation::Environment#dispatcher # DSL method
  max_helper_calls: 0
