AllCops:
  Includes:
    - '../**/*.rake'

# Avoid parameter lists longer than five parameters.
ParameterLists:
  Max: 3
  CountKeywordArgs: true

# Avoid more than `Max` levels of nesting.
BlockNesting:
  Max: 3

# Do not force public/protected/private keyword to be indented at the same
# level as the def keyword. My personal preference is to outdent these keywords
# because I think when scanning code it makes it easier to identify the
# sections of code and visually separate them. When the keyword is at the same
# level I think it sort of blends in with the def keywords and makes it harder
# to scan the code and see where the sections are.
AccessControl:
  Enabled: false

HashSyntax:
  Enabled: false

Blocks:
  Enabled: false

Lambda:
  Enabled: false

SpaceInsideBrackets:
  Enabled: false

Documentation:
  Enabled: false

SingleLineMethods:
  Enabled: false

LineLength:
  Max: 88 # the offending lines are in specs, sadly this means global disabling for now 

MethodLength:
  Max: 12 # reek performs these checks anyway
